#!/bin/bash

git() { LC_ALL=C command git -c color.ui=always "$@"; }

usage() {
    echo "Usage: $(basename "${0}") <git url>" 1>&2
    exit 1
}

URL=""
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        *)
            if [ -z "${URL}" ]; then
                URL="${1}"
            else
                usage
            fi
            ;;
    esac
    shift
done

if [ -z "${URL}" ]; then
    command -v clip-paste &>/dev/null && URL="$(clip-paste)"
    command -v prompt-input &>/dev/null && if ! URL="$(prompt-input "URL:" -d "${URL}")"; then exit 1; fi
fi
[ -z "${URL}" ] && usage

PARENT_DIR="$(pwd)"

abort() {
    echo "Abort." 1>&2
    exit 1
}

if [[ ! "${URL}" =~ ^(https?|ssh)://.* ]] && [[ ! "${URL}" =~ ^git@.* ]]; then
    echo 1>&2
    echo "Looking for repository: ${URL}" 1>&2
    repo="$(git-search "${URL}")"
    if [ -z "${repo}" ]; then
        echo "ERROR: No such repository: ${URL}" 1>&2
        exit 1
    fi
    count=$(echo "${repo}" | wc -l)
    if [ ${count} -gt 1 ]; then
        echo 1>&2
        repo="$(printf '%s\n' "${repo}" | prompt-select -p "Choose repository:")" || abort
    else
        echo "Found repository: ${repo}" 1>&2
    fi
    if [[ "${repo}" =~ github\.com/ ]]; then
        repo_url="$(gh repo view "${repo}" --json sshUrl | jq -r '.sshUrl')"
    else
        repo_url="$(glab repo view "${repo}" -F json | jq -r '.ssh_url_to_repo')"
    fi
    if [ -n "${repo_url}" ]; then
        URL="${repo_url}"
        echo "${URL}" 1>&2
        echo 1>&2
    fi
fi

REPO_PATH=""
if [[ "${URL}" =~ ^git@.* ]]; then
    REPO_PATH="$(echo "${URL}" | cut -d':' -f2-)"
elif [[ "${URL}" =~ ^(https?|ssh)://.* ]]; then
    REPO_PATH="$(echo "${URL}" | cut -d'/' -f4-)"
fi

[ -n "${REPO_PATH}" ] && PARENT_DIR="${WORKSPACE}/$(dirname "${REPO_PATH}")"

PARENT_DIR="$(prompt-folder "Enter parent directory to clone into:" -d "${PARENT_DIR}")" || abort
[ -z "${PARENT_DIR}" ] && abort

mkdir -p "${PARENT_DIR}" 1>&2
cd "${PARENT_DIR}" 1>&2
PARENT_DIR="$(pwd)"

DIR_NAME="$(basename "${URL}" .git)"
if [ -d "${DIR_NAME}" ]; then
    prompt-no-yes "WARNING: ${PARENT_DIR}/${DIR_NAME} already exists, remove it first?" || abort
    rm -rf "${DIR_NAME}" 1>&2
fi

git clone "${URL}" 1>&2
git-find-repo --update-listing
echo "${PARENT_DIR}/${DIR_NAME}"
