#!/bin/bash

usage() {
    cat <<EOF 1>&2
usage: $(basename "${0}") [OPTIONS]

Delete all local branches except the default branch, e.g. "master" or "main".

Options:
    -h, --help    Display this help message.
    -f, --force   Don't prompt for confirmation.
EOF
    exit 1
}

abort() {
    echo "Abort." 1>&2
    exit 1
}

force=0
while [ "${#}" -gt 0 ]; do
    case "${1}" in
        -h|--help) usage ;;
        -f|--force) force=1 ;;
        *) usage ;;
    esac
    shift
done

if [ "${force}" -eq 0 ]; then
    prompt-continue "Are you sure you want to delete all local branches? [y/N]" || abort
fi

default_branch="$(git-default)" || exit 1
local_branches="$(git branch | grep -v "${default_branch}")"
[ -n "${local_branches}" ] && echo "${local_branches}" | xargs git branch -D

exit 0
