#!/bin/bash

function retrieve_tag() {
    local level=$1
    if [ ${level} -eq 0 ]; then
        git describe --tags --abbrev=0 2>/dev/null
    else
        carret=""
        # repeat carret for $level times
        for ((i=0; i<${level}; i++)); do
            carret="${carret}^"
        done
        git describe --tags --abbrev=0 "$(git describe --tags --abbrev=0 2>/dev/null)${carret}" 2>/dev/null
    fi
}

last_tag="$(retrieve_tag "0")"
previous_tag="$(retrieve_tag "1")"

if [ -z "${last_tag}" ]; then
    echo "ERROR: No tags found in repository" 1>&2
    exit 1
fi

# print tag names in bold and previous in red and last in dark green
echo
echo -e "Showing diff of \033[31;1m${previous_tag}\033[0m and \033[32;1m${last_tag}\033[0m"
echo

git diff ${previous_tag} ${last_tag} 2>/dev/null
