#!/bin/bash

usage() {
    cat <<EOF 1>&2
usage: $(basename "${0}") [OPTIONS]

Prints the name of the default remote branch, e.g. "master" or "main".

Options:
    -h, --help                 Show this help message
    --fqn, --fully-qualified   Print the fully qualified name
EOF
    exit 1
}

error() {
    echo "ERROR: ${1}" 1>&2
}

fail() {
    error "${1}"
    exit 1
}

fqn=0

while [ ${#} -gt 0 ]; do
    case "${1}" in
        -h|--help)
            usage
            ;;
        --fqn|--fully-qualified)
            fqn=1
            ;;
        *)
            usage
            ;;
    esac
    shift
done

git_dir="$(git rev-parse --show-toplevel)" || fail "Not a git repo?"

if ref="$(git -C "${git_dir}" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null)"; then
    [ "${fqn}" -eq 0 ] && basename "${ref}" || echo "${ref}"
    exit 0
fi

for branch in main master; do
    if git -C "${git_dir}" show-ref --verify --quiet "refs/heads/${branch}"; then
        [ "${fqn}" -eq 0 ] && echo "${branch}" || echo "refs/heads/${branch}"
        exit 0
    fi
done

fail "No remote HEAD and no local main/master branch found"
